import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider"; // shadcn theme provider
import { Toaster } from "sonner"; // ✅ for toast notifications
import UserNav from "@/components/navview"; // Navigation

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Precious Azoro | Portfolio",
  description:
    "Fullstack Developer | Next.js • React • Node.js • Tailwind • Shadcn",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-[#0a0a0a] text-white transition-colors duration-300`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark" // ✅ dark mode as default
          enableSystem={false} // ✅ disable system preference
          disableTransitionOnChange
        >
          {/* Global toaster notifications */}
          <Toaster
            richColors
            position="top-center"
            expand={true}
            toastOptions={{
              style: { fontSize: "0.95rem", borderRadius: "0.5rem" },
            }}
          />

          {/* Global Navigation */}
          <UserNav />

          {/* Main Page Content */}
          <main className="min-h-screen bg-background pb-24 lg:pb-0">
            {children}
          </main>

          {/* ✅ Floating WhatsApp Button */}
                  {/* ✅ Floating WhatsApp Button — Always visible, even on small screens */}
<a
  href="https://wa.me/2348122844144"
  target="_blank"
  rel="noopener noreferrer"
  className="fixed bottom-6 right-6 group p-0 rounded-2xl shadow-xl hover:scale-110 transition-transform duration-300 z-[9999] block"
>
  {/* WhatsApp Icon Image */}
  <img
    src="https://upload.wikimedia.org/wikipedia/commons/6/6b/WhatsApp.svg"
    alt="WhatsApp"
    className="w-16 h-16 md:w-14 md:h-14 rounded-2xl shadow-lg"
  />

  {/* Hover Tooltip (hidden on mobile automatically due to hover) */}
  <span className="absolute right-20 bg-[#25D366] text-white px-3 py-1 rounded-md opacity-0 group-hover:opacity-100 transition-opacity duration-300 text-sm whitespace-nowrap hidden md:block">
    Chat with me
  </span>
</a>


        </ThemeProvider>
      </body>
    </html>
  );
}









// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// <link href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css" rel="stylesheet" />


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
